version: "3"
services:
  app:
    container_name: developer-manager
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
